example_scroll:
  name: '&aTown Portal'
  lore:
  - Right click to teleport to town
  - '&3The scroll will be consumed'
  loc: 100;200;300;world;270;90
  id: paper
  data: 0
  teleport-msg: '&2You will be teleported soon. (5s)'
  cancel-msg: '&cYou have moved.'
  done-msg: '&eYou have been teleported!'
  fail-msg: '&cYou don''t meet all conditions.'
  delay: 5
  conditions:
  - package.condition
  events:
  - package.event